apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-supplier
spec:
  selector:
    matchLabels:
      app: supplier
  replicas: 1
  template:
    metadata:
      labels:
        app: supplier
    spec:
      containers:
        - name: supplier
          image: k8s-supplier:v1
---
apiVersion: v1
kind: Service
metadata:
  name: supplier
spec:
  selector:
    app: supplier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080